### ISSUE TITLE
Image not defined when testing

### ISSUE THREAD

**Issue by maxhudson** [lavrton/react-konva#76]
I get this error when mounting a shape and layer:

```
ReferenceError: Image is not defined
      at Object.applyNodeProps (client/node_modules/react-konva/src/react-konva.js:224:28)
      at Object.componentDidMount (client/node_modules/react-konva/src/react-konva.js:268:10)
      at client/node_modules/react-dom/lib/ReactCompositeComponent.js:265:25
```

I even get it when running your test:

```
import React from 'react';
import { expect } from 'chai';
import { shallow, mount, render } from 'enzyme';
import {Stage, Layer, Rect} from '../src/react-konva';
import './mocking';
import Konva from 'konva';
import sinon from 'sinon';


describe("Test references", function() {
  let instance;
  class App extends React.Component {
    render() {
      return (
        <Stage ref="stage" width={300} height={300}>
          <Layer ref="layer">
          </Layer>
        </Stage>
      );
    }
  }

  beforeEach(() => {
    const wrapper = mount(<App/>);
    instance = wrapper.instance();
  });

  it("can get stage instance", function() {
    const stageRef = instance.refs.stage;
    expect(stageRef.getStage() instanceof Konva.Stage).to.equal(true);
  });

  it("check initial props set", function() {
    const stage = instance.refs.stage.getStage();
    expect(stage.width()).to.equal(300);
    expect(stage.height()).to.equal(300);
  });

  it("can get layer instance", function() {
    expect(instance.refs.layer instanceof Konva.Layer).to.equal(true);
  });
});
```

Seems like a dependency issue, but I've got `canvas`, `jsdom`, and `konva` installed.

I'm using mocha (but not mocha-phantomjs).

Not seeing anything online about it. Certainly not using any `Image` components. Any ideas?

**Comment by lavrton** [comment]
@maxhudson try this: https://github.com/lavrton/react-konva/issues/60

**Comment by maxhudson** [comment]
@lavrton That did it, even though it's a bit messy. Thanks.
